services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ob_user_task_api_development
    ports:
      - "5440:5432"

  web:
    build: .
    user: "1000:1000" # Use the rails user we created
    command: bash -c "
      bundle config set --local path '/rails/vendor/bundle' &&
      bundle install &&
      ./bin/rails db:prepare &&
      ./bin/rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails:delegated
      # Removed the problematic bundle_cache volume
      # Now using local vendor/bundle directory
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
      BUNDLE_WITHOUT: ""
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      BUNDLE_PATH: /rails/vendor/bundle # Use local path instead
    ports:
      - "3000:3000"
    depends_on:
      - db

  test:
    build: .
    user: "1000:1000"
    command: bash -c "
      bundle config set --local path '/rails/vendor/bundle' &&
      bundle install &&
      bundle exec rspec"
    volumes:
      - .:/rails:delegated
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: test
      BUNDLE_WITHOUT: ""
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      BUNDLE_PATH: /rails/vendor/bundle
    depends_on:
      - db

volumes:
  postgres_data:
  # Removed bundle_cache volume
